# Lista 1 - NumPy

## Exercícios

Para a resolução dos exercícios abaixo, utilize todas as ferramentas e métodos do NumPy aprendidos em aula e existe algumas outras métodos que podem ser úteis na documentação [_NumPy Documentation_](https://numpy.org/doc/). Durante a correção, não será considerado exercícios que não utilizar a ferramenta (muitos deles da pra responder apenas com Python, mas não é esse o intuito da lista).

__Funcionamento dos Exercícios:__ todos os exercícios são do estilo onde será preciso criar uma função para resolver a proposta do enunciado. Será avaliado apenas a função, mas sugiro que crie casos de testes para avaliar se a função está operando corretamente.

__Avaliação e Entrega:__ São 5 exercícios que valem 10 pontos, e a entrega vai ser na forma de um notebook através da tarefa criada no Class.

__Data Limite para Entrega:__ Próxima aula 03/02


### 1) Restaurantes Mais Próximos

Perto da casa de João existem vários restaurantes que entregam comida e João deseja fazer um pedido, mas ele tem um compromisso marcado e não pode esperar muito tempo. Então João quer saber qual é o restaurante mais próximo da residencial dele utilizando da distância Euclidiana, cuja a fórmula é dado pela equação a seguir:

<img align="center" src="https://i.upmath.me/svg/%20d(A%2C%20B)%20%3D%20%5Csqrt%7B(x_%7BA%2C%201%7D%20-%20x_%7BB%2C%201%7D)%5E%7B2%7D%20%2B%20(x_%7BA%2C%202%7D%20-%20x_%7BB%2C%202%7D)%5E%7B2%7D%20%2B%20...%20%2B%20(x_%7BA%2C%20n%7D%20-%20x_%7BB%2C%20n%7D)%5E%7B2%7D%7D" alt=" d(A, B) = \sqrt{(x_{A, 1} - x_{B, 1})^{2} + (x_{A, 2} - x_{B, 2})^{2} + ... + (x_{A, n} - x_{B, n})^{2}}" />

Desenvolva uma função chamada `restaurante_mais_proximo` que irá receber como parâmetros respectivamente __uma lista de coordenadas da casa do João__ e __uma lista com 4 listas com as coordenadas dos restaurantes a verificar__ e o retorno da função deve ser __o número referente ao restaurante mais próximo__. Importante ressaltar que o número do restaurante começa pelo 1 e que em caso de empate, deve-se indicar __o primeiro restaurante a apresentar a menor distância__.

In [3]:
import numpy as np

In [19]:
# exemplo de entrada
# lembrando que pode ter n coordenadas
restaurantes = [[1, 3, 5], [2, 4, 0], [3, 3, 3], [1, 6, 6]]
joao = [0, 1, 2]

In [14]:
def restaurantes_mais_proximos(casa, restaurantes):
    casa = np.array(casa)
    restaurantes = np.array(restaurantes)
    
    distancia_euclidiana = np.sqrt(np.sum((restaurantes - casa)**2, axis = 1))
    
    indice = np.argmin(distancia_euclidiana)
    
    return indice + 1

In [15]:
print(restaurantes_mais_proximos(joao, restaurantes))

1


In [16]:
np.random.seed(42)

joao = np.random.rand(1,3)
print(joao)

restaurantes = np.random.rand(4,3)
print(restaurantes)

[[0.37454012 0.95071431 0.73199394]]
[[0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]]


In [32]:
print(restaurantes_mais_proximos2(joao, restaurantes))

1


In [25]:
def restaurantes_mais_proximos2(casa, restaurantes):
    ar_joao = np.array([casa]*len(restaurantes))
    ar_rest = np.array(restaurantes)
    
    ar_dist = np.linalg.norm(ar_joao - ar_rest, axis = 1)
    
    return np.argmin(ar_dist) + 1

In [21]:
ar_joao = np.array([joao]*len(restaurantes))
print(ar_joao)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [29]:
def restaurantes_mais_proximos3(casa, restaurantes):
    distancias = []
    dist = 0
    
    for i in range(np.array(restaurantes).shape[0]):
        dist = np.linalg.norm(np.array(casa) - np.array(restaurantes[i]))
        distancias.append(dist)
        
    return np.argmin(np.array(distancias)) + 1   

In [31]:
print(restaurantes_mais_proximos3(joao, restaurantes))

1


## 2) Ordenando pelo MMC

O Mínimo Múltiplo Comum (MMC) de dois ou mais números é definido pelo múltiplo comum corresponde a todos os números observados. Por exemplo o MMC entre 6 e 10 é o 30 devido aos número 2, 3 e 5. O objetivo deste exercício, além de calcular o MMC será ordenar a lista utilizando o MMC. Portanto desenvolva a função `ordenar_mmc` onde como entrada irá receber uma lista de números e um número a parte de referência. A função deve calcular O MMC de cada um dos números da lista em relação ao de referência e em seguida ordenar os números originais de acordo com o MMC do menor valor para o maior, como o exemplo a seguir:

```python
# lista de entrada
lista = [12, 8, 10]

# numero de referência
ref = 4

# utilizando a função
print(ordenar_mmc(lista, ref))

# Resultado da função, pois o mmcs = [12, 8, 20] 
[8, 12, 10]
```

In [ ]:
def ordenar_mmc(lista, ref):
    ar_lista = np.array(lista)
    ar_ref = np.array([ref]*len(lista))
    
    mmcs = np.lcm(ar_lista, ar_ref)
    
    ord_idx = np.argsort(mmcs)
    

    return list(ar_lista[ord_idx])

In [61]:
def ordenar_mmc(lista, ref):
    mmcs = np.lcm(lista, ref)
    
    ord_idx = np.argsort(mmcs)
    
    print(ord_idx)
    return [lista[x] for x in ord_idx]

In [34]:
lista = [12, 20, 14, 25, 100, 50, 23]

ref = 5

In [62]:
print(ordenar_mmc(lista, ref))

[1 3 5 0 2 4 6]
[20, 25, 50, 12, 14, 100, 23]


In [47]:
def ordenar_mmc2(lista, ref):
    mmcs = []
    
    for num in lista:
        mmcs.append(np.lcm(num, ref))
        
    return [x for _, x in sorted(zip(mmcs, lista))]

In [48]:
print(ordenar_mmc2(lista, ref))

[20, 25, 50, 12, 14, 100, 23]


In [ ]:
# Explicando o zip dos mmcs

In [37]:
def ordenar_mmc3(lista, ref):
    mmcs = []
    
    for num in lista:
        mmcs.append(np.lcm(num, ref))
        
    return mmcs

In [39]:
mmcs = ordenar_mmc3(lista, ref)
mmcs

[60, 20, 70, 25, 100, 50, 115]

In [42]:
for i in zip(mmcs, lista):
    print(i)

(60, 12)
(20, 20)
(70, 14)
(25, 25)
(100, 100)
(50, 50)
(115, 23)


In [43]:
for i in sorted(zip(mmcs, lista)):
    print(i)

(20, 20)
(25, 25)
(50, 50)
(60, 12)
(70, 14)
(100, 100)
(115, 23)


In [46]:
for _, x in sorted(zip(mmcs, lista)):
    print(x)

20
25
50
12
14
100
23


In [44]:
print(set(zip(mmcs, lista)))

{(115, 23), (100, 100), (25, 25), (20, 20), (50, 50), (70, 14), (60, 12)}


### 3) Normalização ou Z-Score

A normalização (também conhecido como Z-Score) é uma ferramenta muito importante da estatística onde para um conjunto de dados, calcula-se quais serão os respectivos valores se aquele conjunto de dados seguir uma dstribuição normal. O objetivo deste exercício será desenvolver a função `z_score`, onde dado uma lista de entrada com um conjunto de dados quaisquer, devolve a lista com os respectivos Z-Scores dos dados, seguindo a função $z = \frac{x - \mu}{\sigma}$, onde $\mu$ é a média do conjunto de dados e $\sigma$ é o desvio padrão do mesmo (arredonde os valores para 4 casas decimais).

In [63]:
lista = [4, 6, 7, 8, 9]

# primeiro passo = calcular a media da lista
# segundo passo = calcular o desvio padrao
# terceiro passo calcular o z = (x- media)/desvio padrao
# por fim arredonda com o np.round(numero, 4)

In [64]:
def z_score(data):
    arr1 = np.array(data)
    
    mean_arr = np.mean(arr1)
    desvio = np.std(arr1)
    
    z = arr1 - mean_arr
    z = z/desvio
    
    return list(np.round(z, 4))

In [ ]:
def z_score2(data):
    mu = np.mean(data)
    sigma = np.std(data)
    
    zs = []
    for x in data:
        z = np.round((x - mu)/sigma, 4)
        zs.append(z)
        
    return zs

In [65]:
print(z_score(lista))

[-1.6275 -0.465   0.1162  0.6975  1.2787]


### 4) Escalonamento MinMaxScaler

De forma anáçoga a normalização, o MinMaxScaler altera a escala a ser utilizada em um conjunto de dados, onde busca-se os valores máximo e mínimo de um conjunto de dados para depois transformar em uma escala que varia entre esses valores. O objetivo deste exercício será desenvolver uma função chamada `minmaxscaler` que irá receber como entrada um conjunto de dados e de saída será uma lista com os valores na nova escala seguindo a função $y = \frac{x - min}{max - min}$ (arredonde para 3 casas decimais).

In [ ]:
# primeiro passo = calcula o min e max
# segundo passo = calcula o y = (x-min)/(max-min)
# por fim arredonda com 4 casas

In [68]:
def minmaxscaler(data):
    minimo = np.min(data)
    maximo = np.max(data)
    
    escalonamento =[]
    
    for x in data:
        y = np.round((x - minimo)/(maximo - minimo), 3)
        escalonamento.append(y)
        
    return escalonamento

In [69]:
print(minmaxscaler(lista))

[0.0, 0.4, 0.6, 0.8, 1.0]


### 5) Matching entre Vetores

No contexto de Machine Learning, um processo bem comum é de comparar respostas entre vetores para entender o quão acertivo foi um determinado modelo. Dado um contexto, desenvolva a função `vector_matching` que verifica posição a posição destes vetores, que valores de zeros e uns foram acertados. Para esta função têm-se como entrada __dois vetores de dimensões iguais__ preenchidos com 0 ou 1 e a saída da função será o percentual de acerto entre os vetores (arredonde o percentual para 1 casa decimal).

In [71]:
def vector_matching(v1, v2):
    arr_v1 = np.array(v1)
    arr_v2 = np.array(v2)
    
    mask = (arr_v1 == arr_v2).astype(int)
    
    return np.round((np.sum(mask)/len(v1))*100, 1)

In [72]:
print(vector_matching(v1, v2))

50.0


In [73]:
def vector_matching2(v1, v2):
    return np.round((len(np.where(np.array(v1) == np.array(v2))[0])/len(np.array(v1)))*100, 1)

In [74]:
print(vector_matching2(v1, v2))

50.0


In [70]:
v1 = [0, 0, 0, 1, 1, 1, 1, 0]
v2 = [1, 0, 0, 1, 1, 0, 0, 1]

In [75]:
def vector_matching3(v1, v2):
    v1 = np.array(v1)
    v2 = np.array(v2)
    print('v1: ', v1)
    print('v2: ', v2)

    v1 = 1 - v1
    print('v1 invertido: ', v1)
    v2 = np.absolute(v2 - v1)
    print('diferença entre v2 e v1 invertido: ', v2)

    acertos = np.sum(v2)
    print('total de acertos: ', acertos)
    return np.round(acertos/v2.shape[0], 1)  

In [76]:
print(vector_matching3(v1, v2))

v1:  [0 0 0 1 1 1 1 0]
v2:  [1 0 0 1 1 0 0 1]
v1 invertido:  [1 1 1 0 0 0 0 1]
diferença entre v2 e v1 invertido:  [0 1 1 1 1 0 0 0]
total de acertos:  4
0.5


In [ ]:
def vector_matching4(v1, v2):
    return np.round((((np.array(v1) == np.array(v2)).sum())/len(v1))*100, 1)